baseURL: https://openservicemesh.io/
languageCode: en-us
title: Open Service Mesh
theme: clean-landing
enableEmoji: true
disableKinds:
 -taxonomy
 -taxonomyTerm

params:
  description: Open Service Mesh (OSM) is a lightweight, extensible, Cloud Native service mesh
  openGraph: true
  twittersite: openservicemesh
  twittertype: summary_large_image
  twitterimage: images/osm-twitter-card.png
  font:
    name: "Spartan"
    sizes: [400,600]
  navbar:
  - title: Home
    url: /
  - title: Docs
    url: https://docs.openservicemesh.io
  - title: Github
    url: https://github.com/openservicemesh/osm
  - title: Blog
    url: /blog
  - title: Slack
    url: https://cloud-native.slack.com/archives/C018794NV1C
  - title: Twitter
    url: https://twitter.com/openservicemesh
